//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Appoinment
    {
        public int Appointment_ID { get; set; }
        public string Appoinment_Date { get; set; }
        public string Appointment_Time { get; set; }
        public string Appointment_Branch { get; set; }
        public string Appointment_Doctor { get; set; }
        public Nullable<bool> Appointment_Statu { get; set; }
        public string Patient_TC { get; set; }
        public string Patient_Symptom { get; set; }
    }
}
