//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Doctor
    {
        public int Doctor_ID { get; set; }
        public string Doctor_Name { get; set; }
        public string Doctor_LastName { get; set; }
        public string Doctor_Branch { get; set; }
        public string Doctor_TC { get; set; }
        public string Doctor_Password { get; set; }
    }
}
