//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Patient
    {
        public int Patient_ID { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_LastName { get; set; }
        public string Patient_Tc { get; set; }
        public string Patient_Phone { get; set; }
        public string Patient_Password { get; set; }
        public string Patient_Gender { get; set; }
    }
}
